---

- name: Set zsh as the default shell (Linux)
  user: name={{ zsh_user }} shell={{ zsh_user_bin }}
  when: ansible_pkg_mgr != 'homebrew'

- name: Set zsh as the default shell (Homebrew)
  user: name={{ zsh_user }} shell={{ zsh_user_homebrew_path }}/bin/zsh
  when: ansible_pkg_mgr == 'homebrew'
